const products = [
 {"id":"14","name":"Jogo coletivo","type":"camiseta","label":"Camisa de futebol","file":"14-jogo-coletivo","phrase":"NINGUÉM FAZ FILME SOZINHO.","fit":"Camisa de futebol de caimento solto, gola polo com abertura em V e punhos contrastantes.","fabric":"Proposta: malha esportiva de poliéster jacquard, aproximadamente 160–190 g/m², com listras verticais tonais e textura de microfuros a desenvolver com o fornecedor.","print":"ROTA em serifa creme no peito, escudo tipográfico e assinatura a production company. Costas com a frase, número 24 e FRAMES POR SEGUNDO, em referência ao cinema.","finish":"Gola e punhos em creme. Propor escudo aplicado e transfer compatível com poliéster; testar migração de cor, toque e aderência na amostra.","color":"Verde profundo / creme","new":true},
 {"id":"15","name":"Em movimento","type":"corta-vento","label":"Corta-vento com capuz","file":"15-em-movimento","phrase":"KEEP ROLLING","fit":"Amplo, com capuz, zíper frontal completo, mangas raglan, punhos elásticos e ajuste na barra.","fabric":"Proposta: nylon ripstop leve, aproximadamente 100–130 g/m². Reproduzir o toque visual levemente amassado e o brilho discreto do estudo original em amostra física.","print":"Assinatura ROTA pequena no peito. Costas com KEEP ROLLING, CAMERA • BODY • MIND e linha de percurso, preservando a composição original.","finish":"Recortes verdes, filetes creme e puxadores de zíper laranja. Bolsos com zíper. Aplicação compatível com nylon a testar; impermeabilidade não validada.","color":"Grafite / verde profundo / creme / detalhes laranja","new":true},
 {id:'09',name:'Filmmaker On Set',type:'camiseta',label:'Camiseta oversized',file:'09-filmmaker-duas-linhas',phrase:'FILMMAKER ON SET',fit:'Oversized boxy, ombro deslocado, manga ampla próxima ao cotovelo e gola alta de ribana.',fabric:'Proposta: 100% algodão penteado, 260 g/m², pré-encolhido. Confirmar estabilidade dimensional com a confecção.',print:'Serigrafia monocromática em branco-osso. Duas linhas nas costas: FILMMAKER em sans serif alta e condensada; ON SET em serifa itálica. Filetes finos, prisma entre as linhas e assinatura ROTA discreta no peito.',finish:'Costura dupla em barra e mangas; reforço de ombro a ombro; etiqueta tecida na lateral.',color:'Preto / branco-osso',new:true},
 {id:'01',name:'Olhar livre',type:'camiseta',label:'Camiseta oversized',file:'01-olhar-livre',phrase:'Let your eyes wander.',fit:'Oversized, ombros deslocados e manga ampla.',fabric:'Proposta: meia-malha 100% algodão penteado, 240 g/m².',print:'Serigrafia azul sobre base branco-osso; ilustração de câmera e fotógrafo. Prisma discreto na nuca.',finish:'Gola em ribana, reforço interno e barra com costura dupla.',color:'Branco-osso / azul'},
 {id:'02',name:'Pronto pro REC',type:'camiseta',label:'Camiseta oversized',file:'02-pronto-pro-rec',phrase:'Outside the frame.',fit:'Oversized boxy, corpo amplo e gola de ribana.',fabric:'Proposta: 100% algodão penteado, 260 g/m², preto com efeito lavado a validar.',print:'Serigrafia branco-osso e azul. Câmera sobre tripé nas costas; assinatura pequena no peito.',finish:'Teste de lavagem e migração de cor antes de aprovar o efeito lavado.',color:'Preto lavado / branco-osso / azul'},
 {id:'03',name:'Repertório de rua',type:'camiseta',label:'Camiseta ringer',file:'03-repertorio-de-rua',phrase:'Street-fed creativity.',fit:'Ringer de caimento amplo, gola e punhos contrastantes.',fabric:'Proposta: 100% algodão penteado, 240 g/m²; ribana azul compatível com a malha.',print:'Serigrafia azul, com videomaker no skate. Aplicação frontal de maior formato.',finish:'Validar encolhimento entre ribana e corpo; reforço de ombro a ombro.',color:'Branco-osso / azul'},
 {id:'04',name:'Encontro',type:'camiseta',label:'Camiseta oversized',file:'04-encontro',phrase:'Tem coisa que só acontece quando a gente se encontra.',fit:'Oversized, ombro deslocado e comprimento confortável.',fabric:'Proposta: 100% algodão penteado, 240 g/m², tingido em azul.',print:'Serigrafia branco-osso nas costas, com ilustração de amigos à mesa; assinatura frontal pequena.',finish:'Aprovar opacidade da tinta, fidelidade do azul e toque no tecido tingido.',color:'Azul / branco-osso'},
 {id:'05',name:'Polo de produção',type:'moletom',label:'Moletom polo',file:'05-moletom-polo',phrase:'Outside the frame.',fit:'Polo ampla, ombros caídos, gola estruturada e abertura de três botões.',fabric:'Proposta: moletom de 350 g/m², 80% algodão / 20% poliéster; gola com estrutura a validar.',print:'Bordado ROTA no peito; aplicações menores no punho e nas costas. Detalhe azul horizontal.',finish:'Carcela reforçada, punhos e barra em ribana; testar volume do bordado no avesso.',color:'Preto / grafite / azul'},
 {id:'06',name:'Same crew',type:'moletom',label:'Moletom gola careca',file:'06-moletom-same-crew',phrase:'Same crew. Different scene.',fit:'Amplo, gola careca, ombros deslocados e punhos em ribana.',fabric:'Proposta: moletom de 350 g/m², 80% algodão / 20% poliéster, interior felpado.',print:'Serigrafia azul com sequência ilustrada de set, skate e litoral. Prisma pequeno na nuca.',finish:'Testar legibilidade dos traços e resistência à lavagem no tecido escolhido.',color:'Branco-osso / azul'},
 {id:'07',name:'Motion',type:'corta-vento',label:'Corta-vento com zíper',file:'07-corta-vento-motion',phrase:'Always in motion.',fit:'Regular amplo para sobreposição, gola alta e zíper frontal completo; sem capuz.',fabric:'Proposta: nylon ripstop, 100–130 g/m², acabamento repelente à água. Resistência ao vento a validar.',print:'Transfer compatível com nylon ou serigrafia específica, mediante teste. Faixas azuis nas mangas e ROTA nas costas.',finish:'Punhos elásticos, ajuste na barra e proteção interna do zíper. Sem alegação de impermeabilidade.',color:'Preto / azul / branco-osso'},
 {id:'08',name:'Location',type:'corta-vento',label:'Anoraque com capuz',file:'08-corta-vento-location-amarelo',phrase:'Let your eyes wander.',fit:'Anoraque amplo, capuz ajustável, meio zíper e bolso frontal com aba.',fabric:'Proposta: nylon ripstop, 100–130 g/m², com acabamento repelente à água; corpo preto, capuz e ombros amarelo dourado, aba do bolso azul.',print:'Aplicação compatível com o acabamento do nylon. Ilustração olho/diafragma nas costas e assinatura no peito.',finish:'Testar costuras nos recortes e aderência da estampa. Uma versão impermeável exige outra especificação e ensaios.',color:'Preto / amarelo dourado / azul; estampa em marfim'}
];
const lifestyle = p => `assets/${p.file}${p.id==='09'?'-life':'-lifestyle'}.webp`;
const locationName = p => ((Number(p.id)>=6 && Number(p.id)<=8)||p.id==='15') ? 'DOLOMITAS' : 'SÃO PAULO';
const grid=document.querySelector('#products');
const dialog=document.querySelector('#product-dialog');
let lastTrigger;
function render(type='all'){
 grid.innerHTML=products.filter(p=>type==='all'||p.type===type).map(p=>`<article class="product"><button class="product-visual" data-id="${p.id}" aria-label="Ver ${p.name}: imagens e proposta de produção"><img src="${lifestyle(p)}" alt="Campanha conceitual: modelo com ${p.name}, ${p.label.toLowerCase()} ROTA" loading="lazy" width="800" height="1000"><span class="product-tag ${p.new?'new':''}">${p.new?'NOVA PEÇA':locationName(p)}</span><span class="product-plus" aria-hidden="true">+</span></button><div class="product-info"><div><h3>${p.name}</h3><p>${p.label}</p></div><span class="product-index">/${p.id}</span></div></article>`).join('');
 grid.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.id,b)));
}
function openProduct(id,trigger){const p=products.find(p=>p.id===id);lastTrigger=trigger;document.querySelector('#detail-content').innerHTML=`<div class="detail-layout"><div class="detail-gallery"><img src="${lifestyle(p)}" alt="Modelo vestindo ${p.name}; campanha conceitual em ${locationName(p)}"><img class="flat" src="assets/${p.file}.webp" alt="Mockup de frente e costas de ${p.name}"><p class="gallery-caption">CAMPANHA CONCEITUAL / ${locationName(p)}<br>MOCKUP DE FRENTE E COSTAS / ROTA WEAR</p></div><div class="detail-copy"><p class="eyebrow">ROTA WEAR / ${p.id} / ${p.label.toUpperCase()}</p><h2 id="detail-title">${p.name}</h2><p class="detail-phrase">${p.phrase}</p><p class="detail-status">ESPECIFICAÇÃO PROPOSTA · A VALIDAR EM PROTÓTIPO</p><dl>${[['Modelagem',p.fit],['Material',p.fabric],['Estampa e marca',p.print],['Construção e acabamento',p.finish],['Paleta',p.color]].map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl><p class="caption">Gramaturas e composições são pontos de partida para cotação. Medidas, grade, consumo, aplicações e desempenho precisam de ficha técnica e amostra aprovadas.</p></div></div>`;dialog.showModal();document.body.style.overflow='hidden';dialog.scrollTop=0;}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});render(b.dataset.filter);}));
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>{document.body.style.overflow='';lastTrigger?.focus();});
render();

const explorations = [
 {id:'10',file:'10-filmmaker-vinho',name:'Filmmaker / Cinema',subtitle:'Vinho lavado + amarelo-manteiga',colors:['#642735','#eee1a7'],phrase:'FILMMAKER ON SET',direction:'Letras largas, arredondadas e irregulares, com clima de cartaz de cinema dos anos 1970. A frase ocupa as costas; a frente recebe uma assinatura pequena.',production:'Proposta: algodão penteado de aproximadamente 260 g/m², oversized boxy. Serigrafia em amarelo-manteiga. Provar cobertura da tinta clara e estabilidade do efeito lavado.',fit:'Camiseta oversized · estampa tipográfica'},
 {id:'11',file:'11-olhar-musgo',name:'Olhar / Traço livre',subtitle:'Verde-musgo + marfim + laranja',colors:['#555e3e','#f0e4c6','#b75429'],phrase:'Let your eyes wander.',direction:'Desenho de câmera e fotógrafo com traço solto de marcador. A escrita manual aproxima a peça de um caderno de ideias, com uma cor de destaque na lente.',production:'Proposta: algodão penteado de aproximadamente 240 g/m², ombro deslocado. Serigrafia em marfim e laranja. Finalizar espessuras mínimas dos traços e validar a legibilidade no tecido.',fit:'Camiseta oversized · ilustração manual'},
 {id:'12',file:'12-filmmaker-manteiga',name:'Filmmaker / Editorial',subtitle:'Amarelo-manteiga + roxo-berinjela',colors:['#eee0a1','#57234c'],phrase:'Filmmaker / ON SET',direction:'Serifa itálica de alto contraste com “ON SET” pequeno e espaçado. O prisma entra como assinatura; a expressão vem das letras e da combinação de cores.',production:'Proposta: algodão penteado de aproximadamente 240 g/m², corpo amplo. Serigrafia roxa. Ajustar os filetes mais finos da serifa para a impressão e aprovar a cor do tingimento.',fit:'Camiseta oversized · serifa editorial'},
 {id:'13',file:'13-same-crew-marrom',name:'Same crew / Arquibancada',subtitle:'Marrom-café + bege-areia + marfim',colors:['#654a3a','#cdbb9b','#f0e4c6'],phrase:'SAME CREW / DIFFERENT SCENE.',direction:'Letras esportivas e número gráfico 24 sobre corpo marrom-café, com mangas inteiras em bege-areia e ribana chocolate. A câmera nas costas conecta a linguagem de time ao universo da produção audiovisual. O número é um elemento visual desta proposta.',production:'Proposta: algodão penteado de aproximadamente 240 g/m², modelagem ringer ampla. Corpo marrom-café, mangas em bege-areia, ribana chocolate e serigrafia em marfim. Testar encolhimento e solidez da cor entre os diferentes tecidos.',fit:'Camiseta ringer · grafismo esportivo'}
];
document.querySelector('#explorations').innerHTML=explorations.map(p=>`<article class="exploration-card"><button class="exploration-image" data-explore="${p.id}" aria-label="Ampliar estudo ${p.name}"><img src="assets/${p.file}.webp" width="1536" height="1024" loading="lazy" alt="Estudo ${p.name}: frente, costas e modelo vestindo; ${p.subtitle.toLowerCase()}"><span aria-hidden="true">Ampliar +</span></button><div class="exploration-meta"><p class="eyebrow">ESTUDO / ${p.id}</p><div class="swatches" aria-label="${p.subtitle}">${p.colors.map(c=>`<span style="background:${c}"></span>`).join('')}</div></div><h3>${p.name}</h3><p class="exploration-color">${p.subtitle}</p><p>${p.direction}</p></article>`).join('');
document.querySelectorAll('[data-explore]').forEach(button=>button.addEventListener('click',()=>{
 const p=explorations.find(p=>p.id===button.dataset.explore);lastTrigger=button;
 document.querySelector('#detail-content').innerHTML=`<div class="explore-detail"><img src="assets/${p.file}.webp" alt="Frente, costas e modelo vestindo o estudo ${p.name}"><div class="explore-detail-copy"><p class="eyebrow">RODADA 02 / ESTUDO ${p.id}</p><h2 id="detail-title">${p.name}</h2><p class="detail-phrase">${p.phrase}</p><p>${p.direction}</p><dl><dt>Paleta</dt><dd>${p.subtitle}</dd><dt>Modelagem e linguagem</dt><dd>${p.fit}</dd><dt>Produção proposta</dt><dd>${p.production}</dd></dl><p class="caption">Imagem gerada com IA. Cores, arte-final, posição da estampa e medidas precisam de aprovação em protótipo. Este estudo amplia as possibilidades da coleção.</p></div></div>`;
 dialog.showModal();document.body.style.overflow='hidden';dialog.scrollTop=0;
}));
